// Code generated by "stringer -type EventID -trimprefix EventID"; DO NOT EDIT.

package dprotocol

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventIDInputChanged-2]
	_ = x[EventIDOutputChanged-3]
	_ = x[EventIDGpsStatusChanged-5]
	_ = x[EventIDIgnOn-7]
	_ = x[EventIDIgnOff-8]
	_ = x[EventIDNetChanged-9]
	_ = x[EventIDIButton-11]
	_ = x[EventIDPowerSupplyChanged-16]
	_ = x[EventIDTempOK-17]
	_ = x[EventIDTempHigh-18]
	_ = x[EventIDTempLow-19]
	_ = x[EventIDBatteryLow-20]
	_ = x[EventIDBatteryOK-21]
	_ = x[EventIDTachoEvent-23]
	_ = x[EventIDAdSampling-30]
	_ = x[EventIDFuelSampling-31]
	_ = x[EventIDAccOrientation-38]
	_ = x[EventIDSystemInfo-40]
	_ = x[EventIDAccelerometerRapidAcceleration-50]
	_ = x[EventIDAccelerometerHashBraking-51]
	_ = x[EventIDAccelerometerLeftAcceleration-52]
	_ = x[EventIDAccelerometerRightAcceleration-53]
	_ = x[EventIDSoftwareStart-101]
	_ = x[EventIDSoftwareStop-102]
	_ = x[EventIDStartMoving-104]
	_ = x[EventIDStopMoving-105]
	_ = x[EventIDDirectionChanged-106]
	_ = x[EventIDGeofence-107]
	_ = x[EventIDGeofenceDynamic-108]
	_ = x[EventIDAlarmActive-109]
	_ = x[EventIDScheduledEvent-110]
	_ = x[EventIDSpeedLimit-111]
	_ = x[EventIDDistanceTraveled-112]
	_ = x[EventIDADThreshold-113]
	_ = x[EventIDFMSOverspeed-114]
	_ = x[EventIDFMSOvertemp-115]
	_ = x[EventIDFMSOverrevolutions-116]
	_ = x[EventIDFMSHarshBraking-117]
	_ = x[EventIDFMSCruiseControl-118]
	_ = x[EventIDDataEvent-119]
	_ = x[EventIDCommFail-120]
	_ = x[EventIDFlagChanged-121]
	_ = x[EventIDDLKPEmergencyPress-122]
	_ = x[EventIDDLKPStateChanged-123]
	_ = x[EventIDGPSHarshBraking-124]
	_ = x[EventIDGPSRapidAcceleration-125]
	_ = x[EventIDCommSessionClosed-129]
	_ = x[EventIDPCNTData-130]
	_ = x[EventIDPCNTLimit-131]
	_ = x[EventIDPCNTState-132]
	_ = x[EventIDVoiceCall-140]
	_ = x[EventIDHistogramEvent-142]
	_ = x[EventIDFuelLevelEvent-143]
	_ = x[EventIDGarminEvent-160]
	_ = x[EventIDCardDL-170]
	_ = x[EventIDTachoDL-171]
	_ = x[EventIDTemperatureDataEvent-186]
	_ = x[EventIDEBSDataEvent-188]
	_ = x[EventIDCOPUpdate-255]
}

const _EventID_name = "InputChangedOutputChangedGpsStatusChangedIgnOnIgnOffNetChangedIButtonPowerSupplyChangedTempOKTempHighTempLowBatteryLowBatteryOKTachoEventAdSamplingFuelSamplingAccOrientationSystemInfoAccelerometerRapidAccelerationAccelerometerHashBrakingAccelerometerLeftAccelerationAccelerometerRightAccelerationSoftwareStartSoftwareStopStartMovingStopMovingDirectionChangedGeofenceGeofenceDynamicAlarmActiveScheduledEventSpeedLimitDistanceTraveledADThresholdFMSOverspeedFMSOvertempFMSOverrevolutionsFMSHarshBrakingFMSCruiseControlDataEventCommFailFlagChangedDLKPEmergencyPressDLKPStateChangedGPSHarshBrakingGPSRapidAccelerationCommSessionClosedPCNTDataPCNTLimitPCNTStateVoiceCallHistogramEventFuelLevelEventGarminEventCardDLTachoDLTemperatureDataEventEBSDataEventCOPUpdate"

var _EventID_map = map[EventID]string{
	2:   _EventID_name[0:12],
	3:   _EventID_name[12:25],
	5:   _EventID_name[25:41],
	7:   _EventID_name[41:46],
	8:   _EventID_name[46:52],
	9:   _EventID_name[52:62],
	11:  _EventID_name[62:69],
	16:  _EventID_name[69:87],
	17:  _EventID_name[87:93],
	18:  _EventID_name[93:101],
	19:  _EventID_name[101:108],
	20:  _EventID_name[108:118],
	21:  _EventID_name[118:127],
	23:  _EventID_name[127:137],
	30:  _EventID_name[137:147],
	31:  _EventID_name[147:159],
	38:  _EventID_name[159:173],
	40:  _EventID_name[173:183],
	50:  _EventID_name[183:213],
	51:  _EventID_name[213:237],
	52:  _EventID_name[237:266],
	53:  _EventID_name[266:296],
	101: _EventID_name[296:309],
	102: _EventID_name[309:321],
	104: _EventID_name[321:332],
	105: _EventID_name[332:342],
	106: _EventID_name[342:358],
	107: _EventID_name[358:366],
	108: _EventID_name[366:381],
	109: _EventID_name[381:392],
	110: _EventID_name[392:406],
	111: _EventID_name[406:416],
	112: _EventID_name[416:432],
	113: _EventID_name[432:443],
	114: _EventID_name[443:455],
	115: _EventID_name[455:466],
	116: _EventID_name[466:484],
	117: _EventID_name[484:499],
	118: _EventID_name[499:515],
	119: _EventID_name[515:524],
	120: _EventID_name[524:532],
	121: _EventID_name[532:543],
	122: _EventID_name[543:561],
	123: _EventID_name[561:577],
	124: _EventID_name[577:592],
	125: _EventID_name[592:612],
	129: _EventID_name[612:629],
	130: _EventID_name[629:637],
	131: _EventID_name[637:646],
	132: _EventID_name[646:655],
	140: _EventID_name[655:664],
	142: _EventID_name[664:678],
	143: _EventID_name[678:692],
	160: _EventID_name[692:703],
	170: _EventID_name[703:709],
	171: _EventID_name[709:716],
	186: _EventID_name[716:736],
	188: _EventID_name[736:748],
	255: _EventID_name[748:757],
}

func (i EventID) String() string {
	if str, ok := _EventID_map[i]; ok {
		return str
	}
	return "EventID(" + strconv.FormatInt(int64(i), 10) + ")"
}
