// Code generated by "stringer -type Output -trimprefix Output"; DO NOT EDIT.

package dprotocol

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OutputOff-0]
	_ = x[OutputInactive-2]
	_ = x[OutputActive-3]
}

const (
	_Output_name_0 = "Off"
	_Output_name_1 = "InactiveActive"
)

var (
	_Output_index_1 = [...]uint8{0, 8, 14}
)

func (i Output) String() string {
	switch {
	case i == 0:
		return _Output_name_0
	case 2 <= i && i <= 3:
		i -= 2
		return _Output_name_1[_Output_index_1[i]:_Output_index_1[i+1]]
	default:
		return "Output(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
