// Code generated by "stringer -type GPSFlag -trimprefix GPSFlag"; DO NOT EDIT.

package dprotocol

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GPSFlagSpeedOverflow-1]
	_ = x[GPSFlagMaxSpeedOverflow-2]
	_ = x[GPSFlagAssistedGPS-4]
	_ = x[GPSFlagJammingDetected-8]
	_ = x[GPSFlagDualModeGPSFix-16]
	_ = x[GPSFlagDualModeGLONASSFix-32]
	_ = x[GPSFlagFix-64]
	_ = x[GPSFlagCurrentFix-128]
}

const (
	_GPSFlag_name_0 = "SpeedOverflowMaxSpeedOverflow"
	_GPSFlag_name_1 = "AssistedGPS"
	_GPSFlag_name_2 = "JammingDetected"
	_GPSFlag_name_3 = "DualModeGPSFix"
	_GPSFlag_name_4 = "DualModeGLONASSFix"
	_GPSFlag_name_5 = "Fix"
	_GPSFlag_name_6 = "CurrentFix"
)

var (
	_GPSFlag_index_0 = [...]uint8{0, 13, 29}
)

func (i GPSFlag) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _GPSFlag_name_0[_GPSFlag_index_0[i]:_GPSFlag_index_0[i+1]]
	case i == 4:
		return _GPSFlag_name_1
	case i == 8:
		return _GPSFlag_name_2
	case i == 16:
		return _GPSFlag_name_3
	case i == 32:
		return _GPSFlag_name_4
	case i == 64:
		return _GPSFlag_name_5
	case i == 128:
		return _GPSFlag_name_6
	default:
		return "GPSFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
