// Code generated by "stringer -type RadioAccessTechnology -trimprefix RadioAccessTechnology"; DO NOT EDIT.

package dprotocol

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RadioAccessTechnologyUnknown-0]
	_ = x[RadioAccessTechnology2G-2]
	_ = x[RadioAccessTechnology3G-4]
}

const (
	_RadioAccessTechnology_name_0 = "Unknown"
	_RadioAccessTechnology_name_1 = "2G"
	_RadioAccessTechnology_name_2 = "3G"
)

func (i RadioAccessTechnology) String() string {
	switch {
	case i == 0:
		return _RadioAccessTechnology_name_0
	case i == 2:
		return _RadioAccessTechnology_name_1
	case i == 4:
		return _RadioAccessTechnology_name_2
	default:
		return "RadioAccessTechnology(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
