// Code generated by "stringer -type StateFlag -trimprefix StateFlag"; DO NOT EDIT.

package dprotocol

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateFlagCardDL-1]
	_ = x[StateFlagTachographDL-2]
	_ = x[StateFlagIO7-8]
	_ = x[StateFlagIO8-16]
	_ = x[StateFlagIO9-32]
	_ = x[StateFlagIO10-64]
	_ = x[StateFlagIO1-256]
	_ = x[StateFlagIO2-512]
	_ = x[StateFlagIO3-1024]
	_ = x[StateFlagIO4-2048]
	_ = x[StateFlagIO5-4096]
	_ = x[StateFlagIO6-8192]
	_ = x[StateFlagProxyUsage-16384]
	_ = x[StateFlagGSMGPRSJamming-65536]
	_ = x[StateFlagGPSJamming-131072]
	_ = x[StateFlag3PADExtraLED1-524288]
	_ = x[StateFlag3PADExtraLED2-1048576]
	_ = x[StateFlag3PADButtonLED1-2097152]
	_ = x[StateFlag3PADButtonLED2-4194304]
	_ = x[StateFlag3PADButtonLED3-8388608]
}

const _StateFlag_name = "CardDLTachographDLIO7IO8IO9IO10IO1IO2IO3IO4IO5IO6ProxyUsageGSMGPRSJammingGPSJamming3PADExtraLED13PADExtraLED23PADButtonLED13PADButtonLED23PADButtonLED3"

var _StateFlag_map = map[StateFlag]string{
	1:       _StateFlag_name[0:6],
	2:       _StateFlag_name[6:18],
	8:       _StateFlag_name[18:21],
	16:      _StateFlag_name[21:24],
	32:      _StateFlag_name[24:27],
	64:      _StateFlag_name[27:31],
	256:     _StateFlag_name[31:34],
	512:     _StateFlag_name[34:37],
	1024:    _StateFlag_name[37:40],
	2048:    _StateFlag_name[40:43],
	4096:    _StateFlag_name[43:46],
	8192:    _StateFlag_name[46:49],
	16384:   _StateFlag_name[49:59],
	65536:   _StateFlag_name[59:73],
	131072:  _StateFlag_name[73:83],
	524288:  _StateFlag_name[83:96],
	1048576: _StateFlag_name[96:109],
	2097152: _StateFlag_name[109:123],
	4194304: _StateFlag_name[123:137],
	8388608: _StateFlag_name[137:151],
}

func (i StateFlag) String() string {
	if str, ok := _StateFlag_map[i]; ok {
		return str
	}
	return "StateFlag(" + strconv.FormatInt(int64(i), 10) + ")"
}
